// src/styles/homeStyles.ts
import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  topSafe: {
    backgroundColor: "#333C56",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingHorizontal: 24,
    paddingVertical: 12,
    marginTop: Platform.OS === "android" ? 38 : 0,
  },
  topBarSpacer: {
    flex: 1,
  },
  profileButton: {
    padding: 4,
  },
  profileIcon: {
    width: 35,
    height: 35,
    tintColor: "#FFF",
    resizeMode: "contain",
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContainer: {
    position: "absolute",
    top: 50,
    right: 0,
    width: 280,
    backgroundColor: "#333C56",
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    paddingVertical: 12,
  },
  modalHeader: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "700",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#FFF",
    opacity: 0.2,
    marginHorizontal: 16,
  },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  modalButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
    flex: 1,
  },
  modalButtonIcon: {
    width: 20,
    height: 20,
    tintColor: "#FFF",
    resizeMode: "contain",
  },

  changeOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  changeContainer: {
    width: "85%",
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 16,
  },
  changeTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
    textAlign: "center",
  },
  changeInput: {
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 6,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 8,
  },
  errorText: {
    color: "#f66",
    textAlign: "center",
    marginBottom: 8,
  },
  changeButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  cancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  cancelText: {
    color: "#333",
    fontWeight: "500",
  },
  saveButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#333C56",
    borderRadius: 4,
  },
  saveText: {
    color: "#FFF",
    fontWeight: "600",
  },

  bottomSafe: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  calendarContainer: {
    marginHorizontal: 24,
    marginTop: 10,
    borderRadius: 8,
    overflow: "hidden",
    elevation: 1,
    backgroundColor: "#FFF",
  },
  calendar: {
    borderRadius: 8,
  },
  calendarButton: {
    flexDirection: "row",
    backgroundColor: "#E6BC51",
    height: 56,
    marginHorizontal: 24,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    elevation: 2,
    borderWidth: 1,
    borderColor: "rgba(146,114,33,0.3)",
  },
  calendarButtonText: {
    fontSize: 20,
    fontFamily: "Poppins-Bold",
    color: "#927221",
  },
  arrowIcon: {
    width: 26,
    height: 30,
    resizeMode: "contain",
  },

  buttonsWrapper: {
    flexDirection: "row",
    marginHorizontal: 24,
    marginTop: 10,
    height: 232,
  },
  discButton: {
    width: 175,
    height: 232,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 1,
    overflow: "hidden",
    marginRight: 12,
  },
  discButtonBlue: {
    backgroundColor: "#A0BFE8",
  },
  discButtonTriangleTop: {
    width: 140,
    height: 140,
    position: "absolute",
    top: -40,
    right: -2,
    resizeMode: "contain",
  },
  discButtonTriangleBottom: {
    width: 140,
    height: 140,
    position: "absolute",
    bottom: -40,
    left: 0,
    resizeMode: "contain",
  },
  discIcon: {
    position: "absolute",
    top: 16,
    left: 16,
    width: 24.8,
    height: 24.8,
    resizeMode: "contain",
    tintColor: "#4A6FA5",
  },
  discTextWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  discText: {
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Poppins-ExtraBold",
    color: "#FFF",
    textAlign: "center",
  },
  rightColumn: {
    width: 175,
    justifyContent: "space-between",
  },
  smallButton: {
    width: "100%",
    height: "48%",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 1,
    overflow: "hidden",
  },
  smallButtonWhite: {
    backgroundColor: "#FFF",
    borderWidth: 1,
    borderColor: "#DDD",
  },
  smallButtonRed: {
    backgroundColor: "#FF9C9C",
  },
  smallIcon: {
    width: 24.8,
    height: 24.8,
    resizeMode: "contain",
  },
  smallText: {
    marginTop: 8,
    fontSize: 20,
    fontWeight: "600",
    fontFamily: "Poppins-ExtraBold",
  },
  faltaTriangle: {
    width: 184,
    height: 122,
    position: "absolute",
    top: 0,
    right: -20,
    resizeMode: "contain",
  },

  supportButton: {
    flexDirection: "row",
    height: 56,
    backgroundColor: "#333C56",
    marginHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    paddingHorizontal: 24,
    marginTop: 10,
    elevation: 2,
    overflow: "hidden",
  },
  supportButtonGrey: {},
  supportTriangleLeft: {
    width: 175,
    height: 50,
    position: "absolute",
    left: -25,
    top: 8,
    resizeMode: "contain",
    zIndex: 0,
  },
  supportTriangleRight: {
    width: 175,
    height: 50,
    position: "absolute",
    right: -25,
    top: 0,
    resizeMode: "contain",
    zIndex: 0,
  },
  supportText: {
    flex: 1,
    fontSize: 20,
    fontWeight: "600",
    color: "#FFF",
    fontFamily: "Poppins-ExtraBold",
    textAlign: "left",
    zIndex: 1,
  },
  supportIcon: {
    width: 30,
    height: 30,
    tintColor: "#FFF",
    resizeMode: "contain",
    marginLeft: 8,
    zIndex: 1,
  },
  triangleDecor: {
    zIndex: 0,
  },
});
